name: lotf
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adwaita-icon-theme=48.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - apr=1.7.0
  - argcomplete=3.6.2
  - assimp=5.2.5
  - atk-1.0=2.38.0
  - attr=2.5.1
  - bcrypt=4.3.0
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.11.0
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - catkin_pkg=1.0.0
  - catkin_tools=0.9.5
  - certifi=2025.8.3
  - cffi=1.17.1
  - cmake=3.26.3
  - colcon-argcomplete=0.3.3
  - colcon-bash=0.5.0
  - colcon-cd=0.1.1
  - colcon-cmake=0.2.28
  - colcon-common-extensions=0.3.0
  - colcon-core=0.19.0
  - colcon-defaults=0.2.8
  - colcon-devtools=0.3.0
  - colcon-library-path=0.2.1
  - colcon-metadata=0.2.5
  - colcon-output=0.2.13
  - colcon-package-information=0.4.0
  - colcon-package-selection=0.2.10
  - colcon-parallel-executor=0.4.0
  - colcon-pkg-config=0.1.0
  - colcon-powershell=0.4.0
  - colcon-python-setup-py=0.2.9
  - colcon-recursive-crawl=0.2.3
  - colcon-ros=0.5.0
  - colcon-test-result=0.3.8
  - colcon-zsh=0.5.0
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - compilers=1.11.0
  - conda-gcc-specs=14.3.0
  - console_bridge=1.0.2
  - contourpy=1.3.0
  - coreutils=9.5
  - coverage=7.10.4
  - cryptography=42.0.2
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - dbus=1.13.6
  - defusedxml=0.7.1
  - distlib=0.4.0
  - distro=1.9.0
  - docutils=0.22
  - eigen=3.4.0
  - empy=3.3.4
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - fortran-compiler=1.11.0
  - freeglut=3.2.2
  - freeimage=3.18.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdk-pixbuf=2.42.10
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmock=1.17.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - gpgme=1.18.0
  - graphite2=1.3.14
  - graphviz=6.0.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - gtest=1.17.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - hicolor-icon-theme=0.17
  - humanfriendly=10.0
  - icu=70.1
  - imath=3.1.6
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - invoke=2.2.0
  - jack=1.9.22
  - jasper=2.0.33
  - jpeg=9e
  - jxrlib=1.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libapr=1.7.0
  - libapriconv=1.2.2
  - libaprutil=1.6.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libassuan=2.5.7
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.88.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.1.0
  - libgcrypt=1.11.1
  - libgcrypt-devel=1.11.1
  - libgcrypt-lib=1.11.1
  - libgcrypt-tools=1.11.1
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.80.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.6.0
  - libopengl=1.7.0
  - libopengl-devel=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=3.21.12
  - libraw=0.21.1
  - librsvg=2.54.4
  - libsanitizer=14.3.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=253
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libtool=2.5.4
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - log4cxx=0.11.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - make=4.4.1
  - matplotlib-base=3.9.4
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - netifaces=0.11.0
  - nettle=3.9.1
  - ninja=1.13.1
  - nose=1.3.7
  - nspr=4.37
  - nss=3.100
  - numpy=1.26.4
  - ogre=1.10.12
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.8
  - orocos-kdl=1.5.1
  - osrf_pycommon=0.2.1
  - p11-kit=0.24.1
  - packaging=25.0
  - pango=1.50.14
  - paramiko=4.0.0
  - pcre2=10.43
  - pillow=9.4.0
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - pluggy=1.6.0
  - ply=3.11
  - poco=1.12.4
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pugixml=1.11.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - py-opencv=4.6.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycairo=1.25.0
  - pycparser=2.22
  - pycryptodome=3.23.0
  - pycryptodomex=3.23.0
  - pydot=4.0.1
  - pygments=2.19.2
  - pynacl=1.5.0
  - pyopengl=3.1.10
  - pyparsing=3.2.3
  - pyqt=5.15.9
  - pyqt-builder=1.15.4
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pytest=8.4.1
  - pytest-cov=6.2.1
  - pytest-repeat=0.9.4
  - pytest-rerunfailures=15.1
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python-gnupg=0.5.0
  - python-orocos-kdl=1.5.1
  - python_abi=3.9
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - readline=8.2
  - rhash=1.4.3
  - ros-distro-mutex=0.4.0
  - ros-noetic-actionlib=1.14.0
  - ros-noetic-actionlib-msgs=1.13.1
  - ros-noetic-actionlib-tutorials=0.2.0
  - ros-noetic-angles=1.9.13
  - ros-noetic-bond=1.8.6
  - ros-noetic-bond-core=1.8.6
  - ros-noetic-bondcpp=1.8.6
  - ros-noetic-bondpy=1.8.6
  - ros-noetic-catkin=0.8.10
  - ros-noetic-class-loader=0.5.0
  - ros-noetic-cmake-modules=0.5.0
  - ros-noetic-common-msgs=1.13.1
  - ros-noetic-common-tutorials=0.2.0
  - ros-noetic-control-msgs=1.5.2
  - ros-noetic-cpp-common=0.7.2
  - ros-noetic-cv-bridge=1.16.2
  - ros-noetic-desktop=1.5.0
  - ros-noetic-diagnostic-aggregator=1.11.0
  - ros-noetic-diagnostic-analysis=1.11.0
  - ros-noetic-diagnostic-common-diagnostics=1.11.0
  - ros-noetic-diagnostic-msgs=1.13.1
  - ros-noetic-diagnostic-updater=1.11.0
  - ros-noetic-diagnostics=1.11.0
  - ros-noetic-dynamic-reconfigure=1.7.3
  - ros-noetic-eigen-conversions=1.13.2
  - ros-noetic-executive-smach=2.5.0
  - ros-noetic-filters=1.9.2
  - ros-noetic-gencpp=0.7.0
  - ros-noetic-geneus=3.0.0
  - ros-noetic-genlisp=0.4.18
  - ros-noetic-genmsg=0.6.0
  - ros-noetic-gennodejs=2.0.2
  - ros-noetic-genpy=0.6.15
  - ros-noetic-geometry=1.13.2
  - ros-noetic-geometry-msgs=1.13.1
  - ros-noetic-geometry-tutorials=0.2.3
  - ros-noetic-gl-dependency=1.1.2
  - ros-noetic-image-transport=1.12.0
  - ros-noetic-interactive-marker-tutorials=0.11.0
  - ros-noetic-interactive-markers=1.12.0
  - ros-noetic-joint-state-publisher=1.15.1
  - ros-noetic-joint-state-publisher-gui=1.15.1
  - ros-noetic-kdl-conversions=1.13.2
  - ros-noetic-kdl-parser=1.14.2
  - ros-noetic-laser-geometry=1.6.7
  - ros-noetic-librviz-tutorial=0.11.0
  - ros-noetic-map-msgs=1.14.1
  - ros-noetic-media-export=0.3.0
  - ros-noetic-message-filters=1.15.15
  - ros-noetic-message-generation=0.4.1
  - ros-noetic-message-runtime=0.4.13
  - ros-noetic-mk=1.15.8
  - ros-noetic-nav-msgs=1.13.1
  - ros-noetic-nodelet=1.10.2
  - ros-noetic-nodelet-core=1.10.2
  - ros-noetic-nodelet-topic-tools=1.10.2
  - ros-noetic-nodelet-tutorial-math=0.2.0
  - ros-noetic-pluginlib=1.13.0
  - ros-noetic-pluginlib-tutorials=0.2.0
  - ros-noetic-python-qt-binding=0.4.4
  - ros-noetic-qt-dotgraph=0.4.2
  - ros-noetic-qt-gui=0.4.2
  - ros-noetic-qt-gui-cpp=0.4.2
  - ros-noetic-qt-gui-py-common=0.4.2
  - ros-noetic-qwt-dependency=1.1.1
  - ros-noetic-resource-retriever=1.12.7
  - ros-noetic-robot=1.5.0
  - ros-noetic-robot-state-publisher=1.15.2
  - ros-noetic-ros=1.15.8
  - ros-noetic-ros-base=1.5.0
  - ros-noetic-ros-comm=1.15.15
  - ros-noetic-ros-core=1.5.0
  - ros-noetic-ros-environment=1.3.2
  - ros-noetic-ros-tutorials=0.10.2
  - ros-noetic-rosbag=1.16.0
  - ros-noetic-rosbag-migration-rule=1.0.1
  - ros-noetic-rosbag-storage=1.16.0
  - ros-noetic-rosbash=1.15.8
  - ros-noetic-rosboost-cfg=1.15.8
  - ros-noetic-rosbuild=1.15.8
  - ros-noetic-rosclean=1.15.8
  - ros-noetic-rosconsole=1.14.3
  - ros-noetic-rosconsole-bridge=0.5.4
  - ros-noetic-roscpp=1.15.15
  - ros-noetic-roscpp-core=0.7.2
  - ros-noetic-roscpp-serialization=0.7.2
  - ros-noetic-roscpp-traits=0.7.2
  - ros-noetic-roscpp-tutorials=0.10.2
  - ros-noetic-roscreate=1.15.8
  - ros-noetic-rosgraph=1.15.15
  - ros-noetic-rosgraph-msgs=1.11.3
  - ros-noetic-roslang=1.15.8
  - ros-noetic-roslaunch=1.16.0
  - ros-noetic-roslib=1.15.8
  - ros-noetic-roslint=0.12.0
  - ros-noetic-roslisp=1.9.24
  - ros-noetic-roslz4=1.15.15
  - ros-noetic-rosmake=1.15.8
  - ros-noetic-rosmaster=1.15.15
  - ros-noetic-rosmsg=1.15.15
  - ros-noetic-rosnode=1.15.15
  - ros-noetic-rosout=1.15.15
  - ros-noetic-rospack=2.6.2
  - ros-noetic-rosparam=1.15.15
  - ros-noetic-rospy=1.15.15
  - ros-noetic-rospy-tutorials=0.10.2
  - ros-noetic-rosservice=1.15.15
  - ros-noetic-rostest=1.15.15
  - ros-noetic-rostime=0.7.2
  - ros-noetic-rostopic=1.15.15
  - ros-noetic-rosunit=1.15.8
  - ros-noetic-roswtf=1.16.0
  - ros-noetic-rqt-action=0.4.9
  - ros-noetic-rqt-bag=0.5.1
  - ros-noetic-rqt-bag-plugins=0.5.1
  - ros-noetic-rqt-common-plugins=0.4.9
  - ros-noetic-rqt-console=0.4.11
  - ros-noetic-rqt-dep=0.4.12
  - ros-noetic-rqt-graph=0.4.14
  - ros-noetic-rqt-gui=0.5.3
  - ros-noetic-rqt-gui-cpp=0.5.3
  - ros-noetic-rqt-gui-py=0.5.3
  - ros-noetic-rqt-image-view=0.4.16
  - ros-noetic-rqt-launch=0.4.9
  - ros-noetic-rqt-logger-level=0.4.11
  - ros-noetic-rqt-moveit=0.5.10
  - ros-noetic-rqt-msg=0.4.10
  - ros-noetic-rqt-nav-view=0.5.7
  - ros-noetic-rqt-plot=0.4.13
  - ros-noetic-rqt-pose-view=0.5.11
  - ros-noetic-rqt-publisher=0.4.10
  - ros-noetic-rqt-py-common=0.5.3
  - ros-noetic-rqt-py-console=0.4.10
  - ros-noetic-rqt-reconfigure=0.5.5
  - ros-noetic-rqt-robot-dashboard=0.5.8
  - ros-noetic-rqt-robot-monitor=0.5.14
  - ros-noetic-rqt-robot-plugins=0.5.8
  - ros-noetic-rqt-robot-steering=0.5.12
  - ros-noetic-rqt-runtime-monitor=0.5.9
  - ros-noetic-rqt-rviz=0.7.0
  - ros-noetic-rqt-service-caller=0.4.10
  - ros-noetic-rqt-shell=0.4.11
  - ros-noetic-rqt-srv=0.4.9
  - ros-noetic-rqt-tf-tree=0.6.3
  - ros-noetic-rqt-top=0.4.10
  - ros-noetic-rqt-topic=0.4.13
  - ros-noetic-rqt-web=0.4.10
  - ros-noetic-rviz=1.14.19
  - ros-noetic-rviz-plugin-tutorials=0.11.0
  - ros-noetic-rviz-python-tutorial=0.11.0
  - ros-noetic-self-test=1.11.0
  - ros-noetic-sensor-msgs=1.13.1
  - ros-noetic-shape-msgs=1.13.1
  - ros-noetic-smach=2.5.0
  - ros-noetic-smach-msgs=2.5.0
  - ros-noetic-smach-ros=2.5.0
  - ros-noetic-smclib=1.8.6
  - ros-noetic-std-msgs=0.5.13
  - ros-noetic-std-srvs=1.11.3
  - ros-noetic-stereo-msgs=1.13.1
  - ros-noetic-tf=1.13.2
  - ros-noetic-tf-conversions=1.13.2
  - ros-noetic-tf2=0.7.6
  - ros-noetic-tf2-geometry-msgs=0.7.6
  - ros-noetic-tf2-kdl=0.7.6
  - ros-noetic-tf2-msgs=0.7.6
  - ros-noetic-tf2-py=0.7.6
  - ros-noetic-tf2-ros=0.7.6
  - ros-noetic-topic-tools=1.15.15
  - ros-noetic-trajectory-msgs=1.13.1
  - ros-noetic-turtle-actionlib=0.2.0
  - ros-noetic-turtle-tf=0.2.3
  - ros-noetic-turtle-tf2=0.2.3
  - ros-noetic-turtlesim=0.10.2
  - ros-noetic-urdf=1.13.2
  - ros-noetic-urdf-parser-plugin=1.13.2
  - ros-noetic-urdf-tutorial=0.5.0
  - ros-noetic-visualization-marker-tutorials=0.11.0
  - ros-noetic-visualization-msgs=1.13.1
  - ros-noetic-visualization-tutorials=0.11.0
  - ros-noetic-viz=1.5.0
  - ros-noetic-webkit-dependency=1.1.2
  - ros-noetic-xacro=1.14.14
  - ros-noetic-xmlrpcpp=1.15.15
  - rosdep=0.26.0
  - rosdistro=1.0.1
  - rospkg=1.6.0
  - sbcl=2.4.8
  - sdl2=2.26.5
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - svt-av1=1.4.1
  - swig=4.2.1
  - sysroot_linux-64=2.34
  - tinyxml=2.6.2
  - tinyxml2=9.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - typing_extensions=4.14.1
  - unicodedata2=16.0.0
  - unixodbc=2.3.12
  - urdfdom=3.1.1
  - urdfdom_headers=1.1.2
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxaw=1.0.14
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxmu=1.1.3
  - xorg-libxpm=3.5.16
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - zziplib=0.13.69
  - pip:
      - absl-py==2.3.1
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - casadi==3.7.1
      - charset-normalizer==3.4.3
      - chex==0.1.90
      - cloudpickle==3.1.1
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - distrax==0.1.5
      - dm-tree==0.1.8
      - etils==1.5.2
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - flax==0.8.5
      - fqdn==1.5.1
      - fsspec==2025.7.0
      - gast==0.6.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.13.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipykernel==6.30.1
      - ipython==8.18.1
      - isoduration==20.11.0
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jax-dataclasses==1.6.2
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - lark==1.2.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - msgpack==1.1.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.12.0.46
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.27.7
      - nvidia-nvjitlink-cu12==12.9.86
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - overrides==7.7.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.52
      - protobuf==6.32.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyquaternion==0.9.9
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyzmq==27.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - scienceplots==2.1.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.69
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250822
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
